name: blovedream_printer_example
description: Example app for the blovedream_printer plugin.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  blovedream_printer:
    path: ../
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
